// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client/index.ts';
import { client } from './client.gen.ts';
import type {
	DeleteIdByApplicationsByOauthData,
	DeleteIdByFilesByAdminData,
	DeleteIdByShareByDropsByMusicData,
	GetApplicationsByOauthData,
	GetApplicationsByOauthResponses,
	GetArtistsByMusicData,
	GetArtistsByMusicResponses,
	GetArtworkByDropByMusicData,
	GetArtworkBySlugByShareByMusicData,
	GetChatsByWhatsappByMessagingData,
	GetChatsByWhatsappByMessagingResponses,
	GetConversationsByMessagingData,
	GetConversationsByMessagingResponses,
	GetDownloadByClientByApplicationsByOauthData,
	GetDownloadByClientByApplicationsByOauthResponses,
	GetDownloadByDropByDropsByMusicData,
	GetDownloadByDropByDropsByMusicResponses,
	GetDownloadByFileByFilesByAdminData,
	GetDownloadByFileByFilesByAdminResponses,
	GetDownloadBySongBySongsByMusicData,
	GetDownloadBySongBySongsByMusicResponses,
	GetDropsByAdminData,
	GetDropsByAdminResponses,
	GetDropsByMusicData,
	GetDropsByMusicResponses,
	GetFullArtworkByDropByMusicData,
	GetFulldropByMusicData,
	GetFulldropByMusicResponses,
	GetGroupsByAdminData,
	GetGroupsByAdminResponses,
	GetIdByChatsByWhatsappByMessagingData,
	GetIdByChatsByWhatsappByMessagingResponses,
	GetIdByConversationsByMessagingData,
	GetIdByConversationsByMessagingResponses,
	GetIdByDropsByAdminData,
	GetIdByDropsByAdminResponses,
	GetIdByDropsByMusicData,
	GetIdByDropsByMusicResponses,
	GetIdByMyConversationsByMessagingData,
	GetIdByMyConversationsByMessagingResponses,
	GetIdByNotificationsByMessagingData,
	GetIdByNotificationsByMessagingResponses,
	GetIdByPayoutsByPaymentData,
	GetIdByPayoutsByPaymentResponses,
	GetIdByPreferencesByMessagingData,
	GetIdByPreferencesByMessagingResponses,
	GetIdByProviderByPublishByMusicData,
	GetIdByProviderByPublishByMusicResponses,
	GetIdByShareByDropsByMusicData,
	GetIdByShareByDropsByMusicResponses,
	GetIdByShazamByMusicData,
	GetIdByShazamByMusicResponses,
	GetIdBySongsByMusicData,
	GetIdBySongsByMusicResponses,
	GetIdByUserByMessagesByMessagingData,
	GetIdByUserByMessagesByMessagingResponses,
	GetIdByWalletsByAdminData,
	GetIdByWalletsByAdminResponses,
	GetIdByYearInReviewByMusicData,
	GetIdByYearInReviewByMusicResponses,
	GetMyConversationsByMessagingData,
	GetMyConversationsByMessagingResponses,
	GetNotificationsByMessagingData,
	GetNotificationsByMessagingResponses,
	GetPayoutsByAdminData,
	GetPayoutsByAdminResponses,
	GetPayoutsByPaymentData,
	GetPayoutsByPaymentResponses,
	GetPictureByUserByUserData,
	GetProviderByRedirectByAuthData,
	GetQueryBySearchByAdminData,
	GetQueryBySearchByAdminResponses,
	GetServicesByDropByMusicData,
	GetSlugByShareByMusicData,
	GetSongsByMusicData,
	GetSongsByMusicResponses,
	GetTokenByFromUserInteractionByAuthData,
	GetUploadByApplicationsByOauthData,
	GetUploadByAvatarBySetMeByUserData,
	GetUploadByDropByDropsByMusicData,
	GetUploadByPayoutsByAdminData,
	GetUploadBySongsByMusicData,
	GetUserinfoByOauthData,
	GetUserinfoByOauthResponses,
	GetWalletData,
	GetWalletResponses,
	GetWebhookByMetaByMessagingData,
	GetWebhookByStatuspageByIntegrationData,
	PatchIdByApplicationsByOauthData,
	PatchIdByDropsByMusicData,
	PatchIdByNotificationsByMessagingData,
	PatchIdByUsersByUserData,
	PatchIdByWalletsByAdminData,
	PostApplicationsByOauthData,
	PostApplicationsByOauthResponses,
	PostArtistsByMusicData,
	PostArtistsByMusicResponses,
	PostAuthorizeByOauthData,
	PostBugTrackData,
	PostCodeByProviderByOauthByAuthData,
	PostConversationsByMessagingData,
	PostConversationsByMessagingResponses,
	PostDropByDropsByMusicData,
	PostDropByDropsByMusicResponses,
	PostEmailByAuthData,
	PostMusicData,
	PostRefreshAccessTokenByAuthData,
	PostRegisterByAuthData,
	PostResendVerifyEmailByMailByUserData,
	PostResetPasswordByAuthData,
	PostReviewByDropByMusicData,
	PostShareByDropsByMusicData,
	PostShareByDropsByMusicResponses,
	PostSongsByMusicData,
	PostSongsByMusicResponses,
	PostSyncMappingByAdminData,
	PostTokenByOauthData,
	PostTokenByValidateByMailByUserData,
	PostTokenByValidateByPhoneByUserData,
	PostTypeByTypeByDropByMusicData,
	PostValidateByOauthData,
	PostWebhookByMetaByMessagingData,
	PostWebhookByStatuspageByIntegrationData,
	PutPlaceholderByTasksData,
	PutPlaceholderByTasksResponses,
	PutPreferencesByMessagingData,
	PutPreferencesByMessagingResponses,
	PutReadAllByNotificationsByMessagingData,
	PutReadAllByNotificationsByMessagingResponses,
	PutSendByConversationsByMessagingData,
	PutSendByConversationsByMessagingResponses,
	PutUserByUserData,
	PutUserByUserResponses,
	PutWalletData,
	PutWalletResponses,
} from './types.gen.ts';
import {
	zDeleteIdByApplicationsByOauthData,
	zDeleteIdByFilesByAdminData,
	zDeleteIdByShareByDropsByMusicData,
	zGetApplicationsByOauthData,
	zGetApplicationsByOauthResponse,
	zGetArtistsByMusicData,
	zGetArtistsByMusicResponse,
	zGetArtworkByDropByMusicData,
	zGetArtworkBySlugByShareByMusicData,
	zGetChatsByWhatsappByMessagingData,
	zGetChatsByWhatsappByMessagingResponse,
	zGetConversationsByMessagingData,
	zGetConversationsByMessagingResponse,
	zGetDownloadByClientByApplicationsByOauthData,
	zGetDownloadByClientByApplicationsByOauthResponse,
	zGetDownloadByDropByDropsByMusicData,
	zGetDownloadByDropByDropsByMusicResponse,
	zGetDownloadByFileByFilesByAdminData,
	zGetDownloadByFileByFilesByAdminResponse,
	zGetDownloadBySongBySongsByMusicData,
	zGetDownloadBySongBySongsByMusicResponse,
	zGetDropsByAdminData,
	zGetDropsByAdminResponse,
	zGetDropsByMusicData,
	zGetDropsByMusicResponse,
	zGetFullArtworkByDropByMusicData,
	zGetFulldropByMusicData,
	zGetFulldropByMusicResponse,
	zGetGroupsByAdminData,
	zGetGroupsByAdminResponse,
	zGetIdByChatsByWhatsappByMessagingData,
	zGetIdByChatsByWhatsappByMessagingResponse,
	zGetIdByConversationsByMessagingData,
	zGetIdByConversationsByMessagingResponse,
	zGetIdByDropsByAdminData,
	zGetIdByDropsByAdminResponse,
	zGetIdByDropsByMusicData,
	zGetIdByDropsByMusicResponse,
	zGetIdByMyConversationsByMessagingData,
	zGetIdByMyConversationsByMessagingResponse,
	zGetIdByNotificationsByMessagingData,
	zGetIdByNotificationsByMessagingResponse,
	zGetIdByPayoutsByPaymentData,
	zGetIdByPayoutsByPaymentResponse,
	zGetIdByPreferencesByMessagingData,
	zGetIdByPreferencesByMessagingResponse,
	zGetIdByProviderByPublishByMusicData,
	zGetIdByProviderByPublishByMusicResponse,
	zGetIdByShareByDropsByMusicData,
	zGetIdByShareByDropsByMusicResponse,
	zGetIdByShazamByMusicData,
	zGetIdByShazamByMusicResponse,
	zGetIdBySongsByMusicData,
	zGetIdBySongsByMusicResponse,
	zGetIdByUserByMessagesByMessagingData,
	zGetIdByUserByMessagesByMessagingResponse,
	zGetIdByWalletsByAdminData,
	zGetIdByWalletsByAdminResponse,
	zGetIdByYearInReviewByMusicData,
	zGetIdByYearInReviewByMusicResponse,
	zGetMyConversationsByMessagingData,
	zGetMyConversationsByMessagingResponse,
	zGetNotificationsByMessagingData,
	zGetNotificationsByMessagingResponse,
	zGetPayoutsByAdminData,
	zGetPayoutsByAdminResponse,
	zGetPayoutsByPaymentData,
	zGetPayoutsByPaymentResponse,
	zGetPictureByUserByUserData,
	zGetProviderByRedirectByAuthData,
	zGetQueryBySearchByAdminData,
	zGetQueryBySearchByAdminResponse,
	zGetServicesByDropByMusicData,
	zGetSlugByShareByMusicData,
	zGetSongsByMusicData,
	zGetSongsByMusicResponse,
	zGetTokenByFromUserInteractionByAuthData,
	zGetUploadByApplicationsByOauthData,
	zGetUploadByAvatarBySetMeByUserData,
	zGetUploadByDropByDropsByMusicData,
	zGetUploadByPayoutsByAdminData,
	zGetUploadBySongsByMusicData,
	zGetUserinfoByOauthData,
	zGetUserinfoByOauthResponse,
	zGetWalletData,
	zGetWalletResponse,
	zGetWebhookByMetaByMessagingData,
	zGetWebhookByStatuspageByIntegrationData,
	zPatchIdByApplicationsByOauthData,
	zPatchIdByDropsByMusicData,
	zPatchIdByNotificationsByMessagingData,
	zPatchIdByUsersByUserData,
	zPatchIdByWalletsByAdminData,
	zPostApplicationsByOauthData,
	zPostArtistsByMusicData,
	zPostArtistsByMusicResponse,
	zPostAuthorizeByOauthData,
	zPostBugTrackData,
	zPostCodeByProviderByOauthByAuthData,
	zPostConversationsByMessagingData,
	zPostConversationsByMessagingResponse,
	zPostDropByDropsByMusicData,
	zPostDropByDropsByMusicResponse,
	zPostEmailByAuthData,
	zPostMusicData,
	zPostRefreshAccessTokenByAuthData,
	zPostRegisterByAuthData,
	zPostResendVerifyEmailByMailByUserData,
	zPostResetPasswordByAuthData,
	zPostReviewByDropByMusicData,
	zPostShareByDropsByMusicData,
	zPostShareByDropsByMusicResponse,
	zPostSongsByMusicData,
	zPostSongsByMusicResponse,
	zPostSyncMappingByAdminData,
	zPostTokenByOauthData,
	zPostTokenByValidateByMailByUserData,
	zPostTokenByValidateByPhoneByUserData,
	zPostTypeByTypeByDropByMusicData,
	zPostValidateByOauthData,
	zPostWebhookByMetaByMessagingData,
	zPostWebhookByStatuspageByIntegrationData,
	zPutPlaceholderByTasksData,
	zPutPlaceholderByTasksResponse,
	zPutPreferencesByMessagingData,
	zPutPreferencesByMessagingResponse,
	zPutReadAllByNotificationsByMessagingData,
	zPutReadAllByNotificationsByMessagingResponse,
	zPutSendByConversationsByMessagingData,
	zPutSendByConversationsByMessagingResponse,
	zPutUserByUserData,
	zPutUserByUserResponse,
	zPutWalletData,
	zPutWalletResponse,
} from './zod.gen.ts';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: Record<string, unknown>;
};

export const getDropsByAdmin = <ThrowOnError extends boolean = false>(
	options?: Options<GetDropsByAdminData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetDropsByAdminResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetDropsByAdminData.parseAsync(data),
		responseValidator: async (data: any) => await zGetDropsByAdminResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/drops',
		...options,
	});

export const getIdByDropsByAdmin = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByDropsByAdminData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByDropsByAdminResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByDropsByAdminData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdByDropsByAdminResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/drops/{id}',
		...options,
	});

export const getDownloadByFileByFilesByAdmin = <ThrowOnError extends boolean = false>(
	options: Options<GetDownloadByFileByFilesByAdminData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetDownloadByFileByFilesByAdminResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetDownloadByFileByFilesByAdminData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetDownloadByFileByFilesByAdminResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/files/{fileId}/download',
		...options,
	});

export const deleteIdByFilesByAdmin = <ThrowOnError extends boolean = false>(
	options: Options<DeleteIdByFilesByAdminData, ThrowOnError>,
) =>
	(options.client ?? client).delete<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zDeleteIdByFilesByAdminData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/files/{id}',
		...options,
	});

export const getGroupsByAdmin = <ThrowOnError extends boolean = false>(
	options?: Options<GetGroupsByAdminData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetGroupsByAdminResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetGroupsByAdminData.parseAsync(data),
		responseValidator: async (data: any) => await zGetGroupsByAdminResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/groups',
		...options,
	});

export const getPayoutsByAdmin = <ThrowOnError extends boolean = false>(
	options?: Options<GetPayoutsByAdminData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetPayoutsByAdminResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetPayoutsByAdminData.parseAsync(data),
		responseValidator: async (data: any) => await zGetPayoutsByAdminResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/payouts',
		...options,
	});

export const getUploadByPayoutsByAdmin = <ThrowOnError extends boolean = false>(
	options?: Options<GetUploadByPayoutsByAdminData, ThrowOnError>,
) =>
	(options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetUploadByPayoutsByAdminData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/payouts/upload',
		...options,
	});

export const getQueryBySearchByAdmin = <ThrowOnError extends boolean = false>(
	options: Options<GetQueryBySearchByAdminData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetQueryBySearchByAdminResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetQueryBySearchByAdminData.parseAsync(data),
		responseValidator: async (data: any) => await zGetQueryBySearchByAdminResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/search/{query}',
		...options,
	});

export const postSyncMappingByAdmin = <ThrowOnError extends boolean = false>(
	options?: Options<PostSyncMappingByAdminData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostSyncMappingByAdminData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/sync_mapping',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getIdByWalletsByAdmin = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByWalletsByAdminData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByWalletsByAdminResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByWalletsByAdminData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdByWalletsByAdminResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/wallets/{id}',
		...options,
	});

export const patchIdByWalletsByAdmin = <ThrowOnError extends boolean = false>(
	options: Options<PatchIdByWalletsByAdminData, ThrowOnError>,
) =>
	(options.client ?? client).patch<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPatchIdByWalletsByAdminData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/admin/wallets/{id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postEmailByAuth = <ThrowOnError extends boolean = false>(
	options?: Options<PostEmailByAuthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostEmailByAuthData.parseAsync(data),
		url: '/api/@bbn/auth/email',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getTokenByFromUserInteractionByAuth = <ThrowOnError extends boolean = false>(
	options: Options<GetTokenByFromUserInteractionByAuthData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) =>
			await zGetTokenByFromUserInteractionByAuthData.parseAsync(data),
		url: '/api/@bbn/auth/from-user-interaction/{token}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postCodeByProviderByOauthByAuth = <ThrowOnError extends boolean = false>(
	options: Options<PostCodeByProviderByOauthByAuthData, ThrowOnError>,
) =>
	(options.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostCodeByProviderByOauthByAuthData.parseAsync(data),
		url: '/api/@bbn/auth/oauth/{provider}/{code}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getProviderByRedirectByAuth = <ThrowOnError extends boolean = false>(
	options: Options<GetProviderByRedirectByAuthData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetProviderByRedirectByAuthData.parseAsync(data),
		url: '/api/@bbn/auth/redirect/{provider}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postRefreshAccessTokenByAuth = <ThrowOnError extends boolean = false>(
	options?: Options<PostRefreshAccessTokenByAuthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostRefreshAccessTokenByAuthData.parseAsync(data),
		url: '/api/@bbn/auth/refresh-access-token',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const postRegisterByAuth = <ThrowOnError extends boolean = false>(
	options?: Options<PostRegisterByAuthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostRegisterByAuthData.parseAsync(data),
		url: '/api/@bbn/auth/register',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const postResetPasswordByAuth = <ThrowOnError extends boolean = false>(
	options?: Options<PostResetPasswordByAuthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostResetPasswordByAuthData.parseAsync(data),
		url: '/api/@bbn/auth/reset-password',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const postBugTrack = <ThrowOnError extends boolean = false>(
	options?: Options<PostBugTrackData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostBugTrackData.parseAsync(data),
		url: '/api/@bbn/bug-track/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getWebhookByStatuspageByIntegration = <ThrowOnError extends boolean = false>(
	options?: Options<GetWebhookByStatuspageByIntegrationData, ThrowOnError>,
) =>
	(options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) =>
			await zGetWebhookByStatuspageByIntegrationData.parseAsync(data),
		url: '/api/@bbn/integration/statuspage/webhook',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const postWebhookByStatuspageByIntegration = <ThrowOnError extends boolean = false>(
	options?: Options<PostWebhookByStatuspageByIntegrationData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) =>
			await zPostWebhookByStatuspageByIntegrationData.parseAsync(data),
		url: '/api/@bbn/integration/statuspage/webhook',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getConversationsByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<GetConversationsByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetConversationsByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetConversationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) => await zGetConversationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/conversations',
		...options,
	});

export const postConversationsByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<PostConversationsByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).post<PostConversationsByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostConversationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) => await zPostConversationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/conversations',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getIdByConversationsByMessaging = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByConversationsByMessagingData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByConversationsByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByConversationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetIdByConversationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/conversations/{id}',
		...options,
	});

export const putSendByConversationsByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<PutSendByConversationsByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).put<
		PutSendByConversationsByMessagingResponses,
		unknown,
		ThrowOnError
	>({
		requestValidator: async (data: any) => await zPutSendByConversationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zPutSendByConversationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/conversations/send',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getIdByUserByMessagesByMessaging = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByUserByMessagesByMessagingData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByUserByMessagesByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByUserByMessagesByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetIdByUserByMessagesByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/messages/{userId}/{id}',
		...options,
	});

export const getWebhookByMetaByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<GetWebhookByMetaByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetWebhookByMetaByMessagingData.parseAsync(data),
		url: '/api/@bbn/messaging/meta/webhook',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const postWebhookByMetaByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<PostWebhookByMetaByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostWebhookByMetaByMessagingData.parseAsync(data),
		url: '/api/@bbn/messaging/meta/webhook',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getMyConversationsByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<GetMyConversationsByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetMyConversationsByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetMyConversationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetMyConversationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/my-conversations',
		...options,
	});

export const getIdByMyConversationsByMessaging = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByMyConversationsByMessagingData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByMyConversationsByMessagingResponses, unknown, ThrowOnError>(
		{
			requestValidator: async (data: any) =>
				await zGetIdByMyConversationsByMessagingData.parseAsync(data),
			responseValidator: async (data: any) =>
				await zGetIdByMyConversationsByMessagingResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/@bbn/messaging/my-conversations/{id}',
			...options,
		},
	);

export const getNotificationsByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<GetNotificationsByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetNotificationsByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetNotificationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) => await zGetNotificationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/notifications',
		...options,
	});

export const getIdByNotificationsByMessaging = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByNotificationsByMessagingData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByNotificationsByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByNotificationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetIdByNotificationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/notifications/{id}',
		...options,
	});

export const patchIdByNotificationsByMessaging = <ThrowOnError extends boolean = false>(
	options: Options<PatchIdByNotificationsByMessagingData, ThrowOnError>,
) =>
	(options.client ?? client).patch<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPatchIdByNotificationsByMessagingData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/notifications/{id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const putReadAllByNotificationsByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<PutReadAllByNotificationsByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).put<
		PutReadAllByNotificationsByMessagingResponses,
		unknown,
		ThrowOnError
	>({
		requestValidator: async (data: any) =>
			await zPutReadAllByNotificationsByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zPutReadAllByNotificationsByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/notifications/read-all',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const putPreferencesByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<PutPreferencesByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).put<PutPreferencesByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPutPreferencesByMessagingData.parseAsync(data),
		responseValidator: async (data: any) => await zPutPreferencesByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/preferences',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getIdByPreferencesByMessaging = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByPreferencesByMessagingData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByPreferencesByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByPreferencesByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetIdByPreferencesByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/preferences/{id}',
		...options,
	});

export const getChatsByWhatsappByMessaging = <ThrowOnError extends boolean = false>(
	options?: Options<GetChatsByWhatsappByMessagingData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetChatsByWhatsappByMessagingResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetChatsByWhatsappByMessagingData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetChatsByWhatsappByMessagingResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/messaging/whatsapp/chats',
		...options,
	});

export const getIdByChatsByWhatsappByMessaging = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByChatsByWhatsappByMessagingData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByChatsByWhatsappByMessagingResponses, unknown, ThrowOnError>(
		{
			requestValidator: async (data: any) =>
				await zGetIdByChatsByWhatsappByMessagingData.parseAsync(data),
			responseValidator: async (data: any) =>
				await zGetIdByChatsByWhatsappByMessagingResponse.parseAsync(data),
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/api/@bbn/messaging/whatsapp/chats/{id}',
			...options,
		},
	);

export const postMusic = <ThrowOnError extends boolean = false>(
	options?: Options<PostMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getArtworkByDropByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetArtworkByDropByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetArtworkByDropByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/{dropId}/artwork',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getFullArtworkByDropByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetFullArtworkByDropByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetFullArtworkByDropByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/{dropId}/fullArtwork',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postReviewByDropByMusic = <ThrowOnError extends boolean = false>(
	options: Options<PostReviewByDropByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostReviewByDropByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/{dropId}/review',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getServicesByDropByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetServicesByDropByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetServicesByDropByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/{dropId}/services',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postTypeByTypeByDropByMusic = <ThrowOnError extends boolean = false>(
	options: Options<PostTypeByTypeByDropByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostTypeByTypeByDropByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/{dropId}/type/{type}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getArtistsByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<GetArtistsByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetArtistsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetArtistsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetArtistsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/artists',
		...options,
	});

export const postArtistsByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<PostArtistsByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).post<PostArtistsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostArtistsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zPostArtistsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/artists',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getDropsByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<GetDropsByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetDropsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetDropsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetDropsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops',
		...options,
	});

export const postDropByDropsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<PostDropByDropsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).post<PostDropByDropsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostDropByDropsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zPostDropByDropsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/{dropId}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getDownloadByDropByDropsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetDownloadByDropByDropsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetDownloadByDropByDropsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetDownloadByDropByDropsByMusicData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetDownloadByDropByDropsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/{dropId}/download',
		...options,
	});

export const getUploadByDropByDropsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetUploadByDropByDropsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetUploadByDropByDropsByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/{dropId}/upload',
		...options,
	});

export const getIdByDropsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByDropsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByDropsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByDropsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdByDropsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/{id}',
		...options,
	});

export const patchIdByDropsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<PatchIdByDropsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).patch<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPatchIdByDropsByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/{id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postShareByDropsByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<PostShareByDropsByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).post<PostShareByDropsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostShareByDropsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zPostShareByDropsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/share',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const deleteIdByShareByDropsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<DeleteIdByShareByDropsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).delete<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zDeleteIdByShareByDropsByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/share/{id}',
		...options,
	});

export const getIdByShareByDropsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByShareByDropsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByShareByDropsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByShareByDropsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdByShareByDropsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/drops/share/{id}',
		...options,
	});

export const getFulldropByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<GetFulldropByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetFulldropByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetFulldropByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetFulldropByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/fulldrop',
		...options,
	});

export const getIdByProviderByPublishByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByProviderByPublishByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByProviderByPublishByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByProviderByPublishByMusicData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetIdByProviderByPublishByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/publish/{provider}/{id}',
		...options,
	});

export const getSlugByShareByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetSlugByShareByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetSlugByShareByMusicData.parseAsync(data),
		url: '/api/@bbn/music/share/{slug}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getArtworkBySlugByShareByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetArtworkBySlugByShareByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetArtworkBySlugByShareByMusicData.parseAsync(data),
		url: '/api/@bbn/music/share/{slug}/artwork',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getIdByShazamByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByShazamByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByShazamByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByShazamByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdByShazamByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/shazam/{id}',
		...options,
	});

export const getSongsByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<GetSongsByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetSongsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetSongsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetSongsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/songs',
		...options,
	});

export const postSongsByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<PostSongsByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).post<PostSongsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostSongsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zPostSongsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/songs',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getIdBySongsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetIdBySongsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdBySongsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdBySongsByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdBySongsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/songs/{id}',
		...options,
	});

export const getDownloadBySongBySongsByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetDownloadBySongBySongsByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetDownloadBySongBySongsByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetDownloadBySongBySongsByMusicData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetDownloadBySongBySongsByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/songs/{songId}/download',
		...options,
	});

export const getUploadBySongsByMusic = <ThrowOnError extends boolean = false>(
	options?: Options<GetUploadBySongsByMusicData, ThrowOnError>,
) =>
	(options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetUploadBySongsByMusicData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/songs/upload',
		...options,
	});

export const getIdByYearInReviewByMusic = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByYearInReviewByMusicData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByYearInReviewByMusicResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByYearInReviewByMusicData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdByYearInReviewByMusicResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/music/year-in-review/{id}',
		...options,
	});

export const getApplicationsByOauth = <ThrowOnError extends boolean = false>(
	options?: Options<GetApplicationsByOauthData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetApplicationsByOauthResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetApplicationsByOauthData.parseAsync(data),
		responseValidator: async (data: any) => await zGetApplicationsByOauthResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/applications',
		...options,
	});

export const postApplicationsByOauth = <ThrowOnError extends boolean = false>(
	options?: Options<PostApplicationsByOauthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<PostApplicationsByOauthResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostApplicationsByOauthData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/applications',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getDownloadByClientByApplicationsByOauth = <ThrowOnError extends boolean = false>(
	options: Options<GetDownloadByClientByApplicationsByOauthData, ThrowOnError>,
) =>
	(options.client ?? client).get<
		GetDownloadByClientByApplicationsByOauthResponses,
		unknown,
		ThrowOnError
	>({
		requestValidator: async (data: any) =>
			await zGetDownloadByClientByApplicationsByOauthData.parseAsync(data),
		responseValidator: async (data: any) =>
			await zGetDownloadByClientByApplicationsByOauthResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/applications/{clientId}/download',
		...options,
	});

export const deleteIdByApplicationsByOauth = <ThrowOnError extends boolean = false>(
	options: Options<DeleteIdByApplicationsByOauthData, ThrowOnError>,
) =>
	(options.client ?? client).delete<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zDeleteIdByApplicationsByOauthData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/applications/{id}',
		...options,
	});

export const patchIdByApplicationsByOauth = <ThrowOnError extends boolean = false>(
	options: Options<PatchIdByApplicationsByOauthData, ThrowOnError>,
) =>
	(options.client ?? client).patch<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPatchIdByApplicationsByOauthData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/applications/{id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getUploadByApplicationsByOauth = <ThrowOnError extends boolean = false>(
	options?: Options<GetUploadByApplicationsByOauthData, ThrowOnError>,
) =>
	(options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetUploadByApplicationsByOauthData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/applications/upload',
		...options,
	});

export const postAuthorizeByOauth = <ThrowOnError extends boolean = false>(
	options?: Options<PostAuthorizeByOauthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostAuthorizeByOauthData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/authorize',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const postTokenByOauth = <ThrowOnError extends boolean = false>(
	options?: Options<PostTokenByOauthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostTokenByOauthData.parseAsync(data),
		url: '/api/@bbn/oauth/token',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getUserinfoByOauth = <ThrowOnError extends boolean = false>(
	options?: Options<GetUserinfoByOauthData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetUserinfoByOauthResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetUserinfoByOauthData.parseAsync(data),
		responseValidator: async (data: any) => await zGetUserinfoByOauthResponse.parseAsync(data),
		url: '/api/@bbn/oauth/userinfo',
		...options,
	});

export const postValidateByOauth = <ThrowOnError extends boolean = false>(
	options?: Options<PostValidateByOauthData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostValidateByOauthData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/oauth/validate',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getPayoutsByPayment = <ThrowOnError extends boolean = false>(
	options?: Options<GetPayoutsByPaymentData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetPayoutsByPaymentResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetPayoutsByPaymentData.parseAsync(data),
		responseValidator: async (data: any) => await zGetPayoutsByPaymentResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/payment/payouts',
		...options,
	});

export const getIdByPayoutsByPayment = <ThrowOnError extends boolean = false>(
	options: Options<GetIdByPayoutsByPaymentData, ThrowOnError>,
) =>
	(options.client ?? client).get<GetIdByPayoutsByPaymentResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetIdByPayoutsByPaymentData.parseAsync(data),
		responseValidator: async (data: any) => await zGetIdByPayoutsByPaymentResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/payment/payouts/{id}',
		...options,
	});

export const putPlaceholderByTasks = <ThrowOnError extends boolean = false>(
	options?: Options<PutPlaceholderByTasksData, ThrowOnError>,
) =>
	(options?.client ?? client).put<PutPlaceholderByTasksResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPutPlaceholderByTasksData.parseAsync(data),
		responseValidator: async (data: any) => await zPutPlaceholderByTasksResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/tasks/placeholder',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const getPictureByUserByUser = <ThrowOnError extends boolean = false>(
	options: Options<GetPictureByUserByUserData, ThrowOnError>,
) =>
	(options.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetPictureByUserByUserData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/user/{userId}/picture',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postResendVerifyEmailByMailByUser = <ThrowOnError extends boolean = false>(
	options?: Options<PostResendVerifyEmailByMailByUserData, ThrowOnError>,
) =>
	(options?.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostResendVerifyEmailByMailByUserData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/user/mail/resend-verify-email',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const postTokenByValidateByMailByUser = <ThrowOnError extends boolean = false>(
	options: Options<PostTokenByValidateByMailByUserData, ThrowOnError>,
) =>
	(options.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostTokenByValidateByMailByUserData.parseAsync(data),
		url: '/api/@bbn/user/mail/validate/{token}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const postTokenByValidateByPhoneByUser = <ThrowOnError extends boolean = false>(
	options: Options<PostTokenByValidateByPhoneByUserData, ThrowOnError>,
) =>
	(options.client ?? client).post<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPostTokenByValidateByPhoneByUserData.parseAsync(data),
		url: '/api/@bbn/user/phone/validate/{token}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getUploadByAvatarBySetMeByUser = <ThrowOnError extends boolean = false>(
	options?: Options<GetUploadByAvatarBySetMeByUserData, ThrowOnError>,
) =>
	(options?.client ?? client).get<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetUploadByAvatarBySetMeByUserData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/user/set-me/avatar/upload',
		...options,
	});

export const putUserByUser = <ThrowOnError extends boolean = false>(
	options?: Options<PutUserByUserData, ThrowOnError>,
) =>
	(options?.client ?? client).put<PutUserByUserResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPutUserByUserData.parseAsync(data),
		responseValidator: async (data: any) => await zPutUserByUserResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/user/user',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});

export const patchIdByUsersByUser = <ThrowOnError extends boolean = false>(
	options: Options<PatchIdByUsersByUserData, ThrowOnError>,
) =>
	(options.client ?? client).patch<unknown, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPatchIdByUsersByUserData.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/user/users/{id}',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options.headers,
		},
	});

export const getWallet = <ThrowOnError extends boolean = false>(
	options?: Options<GetWalletData, ThrowOnError>,
) =>
	(options?.client ?? client).get<GetWalletResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zGetWalletData.parseAsync(data),
		responseValidator: async (data: any) => await zGetWalletResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/wallet/',
		...options,
	});

export const putWallet = <ThrowOnError extends boolean = false>(
	options?: Options<PutWalletData, ThrowOnError>,
) =>
	(options?.client ?? client).put<PutWalletResponses, unknown, ThrowOnError>({
		requestValidator: async (data: any) => await zPutWalletData.parseAsync(data),
		responseValidator: async (data: any) => await zPutWalletResponse.parseAsync(data),
		security: [{ scheme: 'bearer', type: 'http' }],
		url: '/api/@bbn/wallet/',
		...options,
		headers: {
			'Content-Type': 'application/json',
			...options?.headers,
		},
	});
