<script lang="ts">
	import { Heading } from '$lib/components/ui';
</script>

<svelte:head>
	<title>Terms and Conditions - bbn.music</title>
</svelte:head>

<div class="max-w-4xl mx-auto space-y-6">
	<Heading tag="h1" class="text-white">Terms and Conditions</Heading>

	<div class="prose prose-invert max-w-none space-y-6 text-gray-300">
		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Definitions</Heading>
			<p>
				To facilitate the understanding of these Terms of Use, the following principal expressions
				will have these meanings:
			</p>
			<ul class="list-none space-y-3">
				<li>
					<strong>"Customer":</strong> refers to any individual that accesses or makes use of a Digital
					Music Service.
				</li>
				<li>
					<strong>"Digital Distribution":</strong> means the transferring by any means of data transmission
					or communication, through the internet, internet radio, kiosks, in-store listening posts, mobile,
					wireless, satellite and similar communication systems, whether now known or existing in the
					future, of the End User Content in multiple digital formats including but not limited to clips,
					permanent downloads, subscriptions, streams and timeout-downloads, ring-tones and ring-back
					tones and any other means.
				</li>
				<li>
					<strong>"Digital Music Service":</strong> means any digital outlet, such as music download portals,
					music and video streaming services, mobile music platforms, digital (and terrestrial) radio
					stations, digital (and terrestrial) television networks, and mobile networks (each a "DMS",
					i.e.: Apple iTunes, Spotify, Tidal, Google Play, etc.), that enables Customers to purchase and/or
					listen to End User Content.
				</li>
				<li>
					<strong>"End User":</strong> that's You (hereinafter, the End User), which is an artist, songwriter,
					author, producer, agent (including royalty recipients), rights holder or others who are authorized
					and entitled to exploit certain music (including the composition and the recording) and to use
					the Platform, the Platform API or portions thereof.
				</li>
				<li>
					<strong>"End User Content":</strong> means all intellectual property works (including without
					limitation musical works, recordings, video clips, ring-tones, real-tones, lyrics, logos, covers
					and photos) as to which the End User has the necessary exploitation rights, including "Neighboring
					Rights".
				</li>
				<li>
					<strong>"Platform":</strong> refers to the digital music distribution platform available at
					https://bbn.music/c/music or your designated subdomain.
				</li>
				<li>
					<strong>"Service":</strong> means the service provided by Us through the Platform, in order
					to make the End User Content available on Digital Music Services (here, the Digital Distribution
					Services).
				</li>
			</ul>
			<p>Hence, these are the rights and obligations of each of us:</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold"
				>General Conditions; Access to and use of the Services</Heading
			>
			<p>
				<strong>2.1</strong> During the Duration and subject to compliance by You with these Terms of
				Use, You have the right to access the Platform and enjoy the Service provided by Us through it.
			</p>
			<p>
				<strong>2.2</strong> For information purposes, the features of the Platform include but are not
				limited to:
			</p>
			<ul class="list-disc pl-6 space-y-1">
				<li>
					Upload of the End User Content to the Platform for its availability on Digital Music
					Services.
				</li>
				<li>
					Selection of the channels, territories and Digital Music Services where End Users want
					their content to be available at.
				</li>
				<li>Optional services, including quality control, distribution, updates and storage.</li>
				<li>Pay directly the corresponding fees for the contracting services.</li>
				<li>Hosting of the End User Content.</li>
				<li>Qualification, transformation and transmission to Digital Music Services.</li>
				<li>Updating of distributed works in Digital Music Services.</li>
				<li>Takedown of content.</li>
				<li>Assigning codes (ISRC, UPC, ISWC).</li>
				<li>
					Accessing sales and usage reports of the End User Content in the Digital Music Services.
				</li>
				<li>Request out-payment of the Royalties generated by the End User Content.</li>
				<li>Manage and receive neighboring rights.</li>
			</ul>
			<p>
				Nonetheless, We reserve the right to include new functionalities or eliminate any of the
				features of the Service, to change the characteristics, design, appearance or presentation
				of the Platform and the Service. In such case, if You are unsatisfied with the resulting
				Platform, You may terminate the relationship pursuant to Section 5.
			</p>
			<p>
				<strong>2.3</strong> Furthermore, You warrant that You have all necessary rights in respect of
				Your Content to exploit it through the Platform and, therefore, authorize Us to administer Your
				Content as requested by You at each time, in the terms described in Section 6. This authorization
				is granted on an exclusive basis for those Digital Music Services on which You decide to make
				Your Content available through our Service; this means that if You use the Service to make Your
				Content available in a specific Digital Music Service, You may not make the same content available
				in the same Digital Music Service using a service different from the Service and the Platform.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold"
				>What You can do and what you can't do</Heading
			>
			<p class="font-semibold">Use of the Platform</p>
			<p>
				<strong>3.1</strong> By registering and uploading Your Content on the Platform, You assume and
				undertake the following obligations:
			</p>
			<ul class="list-disc pl-6 space-y-1">
				<li>
					You shall use the Platform diligently and upload information and content whose rights
					belong to You or for which You are authorized by the rights holder.
				</li>
				<li>
					You shall provide all the necessary information to use the Service, which We will request
					during the use of the Service.
				</li>
				<li>
					You shall pay all the applicable fees for the Services rendered by Us, as described below.
				</li>
				<li>You shall inform Us of any activity that is inconsistent with these Terms of Use.</li>
				<li>
					You shall indicate through the Platform if Your Content contains "explicit" content. The
					term "explicit" content refers to content that evokes sexual, racist, violent or any other
					harmful connotations.
				</li>
				<li>
					You shall not perform illegal activities through the Platform or the Services, and/or
					actions that could harm or damage any party, including Us.
				</li>
			</ul>
			<p><strong>3.2</strong> You undertake to use diligently the Platform and agree:</p>
			<ul class="list-disc pl-6 space-y-1">
				<li>
					not to grant access to the Platform to any third party or to employees that, due to their
					position in the company, reasonably should not access the Platform;
				</li>
				<li>not to access the source code of the Platform;</li>
				<li>
					not to use the information, rules or instructions contained in the Platform for purposes
					different than those established in these Terms of Use;
				</li>
				<li>
					not to disclose to any third party any of the information obtained through the Platform;
				</li>
				<li>
					not to permit the public to access or use the Platform (including, without limitation, via
					the internet);
				</li>
				<li>
					not to use the Platform to upload content not owned by You or for which You do not have an
					explicit license to commercially exploit;
				</li>
				<li>not to reproduce the Platform, in whole or in part, for any purposes;</li>
				<li>not to copy and/or distribute the Platform, in whole or in part, by any manner;</li>
				<li>
					not to create any form of "frame" or "mirror" for (any part of) the Platform on any other
					server or wireless or Internet-based device;
				</li>
				<li>not to transfer the Platform to any third party;</li>
				<li>
					not to assign, sell, resell, rent, lease, lend, sublicense, outsource or otherwise
					transfer the Platform and/or the Service to any third party, or authorize or appoint any
					third party to do so;
				</li>
				<li>not to modify the Platform or provide any person with the means to do the same;</li>
				<li>
					not to circumvent the technological protection measures incorporated in the Platform.
				</li>
			</ul>
			<p>
				<strong>3.3</strong> In general, You agree to use the Platform in a lawful and diligent manner
				and will not do anything forbidden by law or by these Terms of Use. You will be liable to Us for
				any breach of these Terms, as described in Section 9.
			</p>

			<p class="font-semibold mt-4">User Warranties</p>
			<p>
				<strong>3A.1</strong> You represent and warrant that you own or have obtained all rights, licenses,
				consents and permissions necessary to upload, reproduce, distribute and otherwise exploit Your
				Content via the Service in each territory selected. Such rights shall be irrevocable with respect
				to any distribution already made.
			</p>
			<p>
				<strong>3A.2</strong> You undertake that no portion of Your Content is subject to a right of revocation
				that would allow You or any third party to demand removal once the Content has been distributed
				through the Platform.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Fees</Heading>
			<p>
				<strong>4.1</strong> By using the Service, You shall pay to Us the fees corresponding to the Services
				contracted, which can be found at any time in the "My Account > Pricing" section of your Account.
			</p>
			<p>
				Additionally, You will receive 100.00% of the net incomes (deducting expenses and taxes)
				which We receive from Digital Music Services from the exploitation of Your Content. If
				applicable, You authorize Us to deduct 0% sales commission percentage from the net incomes
				received by Us from Digital Music Services.
			</p>
			<p>
				The abovementioned Service fees, sales commission percentage and the minimum payment
				threshold for You are listed in the Platform, in the "My Account > Pricing" section.
			</p>
			<p>
				<strong>4.2</strong> All payments and associated claims: (i) will be made through the corresponding
				"Sales->Balance" section of the Platform; (ii) will be made in the currency stated by Us; and
				(iii) will be payable via PayPal or bank-to-bank wire transfer to the account designated by You.
				If any authority imposes a duty, tax, levy, or fee, You agree to pay that amount or supply exemption
				documentation.
			</p>
			<p>
				Payment of generated sales fees under these Terms of Use shall be made on a once a month,
				within days from receipt of an out payment request from you, provided always that the due
				amount exceeds the corresponding minimum payment threshold for the relevant requested
				payout.
			</p>
			<p>
				<strong>4.3</strong> If any Digital Music Service deducts any amount due to any passed contingency,
				overpayment or conclusion in relation to Your Content or an investigation by Us reasonably demonstrates
				that any of Your fees for any prior month should have been lesser, We may, at the conclusion of
				such investigation and at our sole discretion, provide a revised sales report for the applicable
				month(s) and deduct the corresponding amount from future payments, what You acknowledge and accept.
			</p>
			<p>
				<strong>4.4</strong> Therefore, You expressly and irrevocably authorize Us to collect all incomes
				from the exploitation of Your Content through the Platform, including but not limited to author
				rights, performing and recording rights, any levy established by law for private copies, or for
				any other concept, without limitation.
			</p>
			<p>
				<strong>4.5</strong> We will make any corresponding invoices and receipts, including mandatory
				taxes, available to You according to the applicable regulations.
			</p>
			<p>
				<strong>4.6</strong> We reserve the right to change in the future the Service price, the sales
				commission percentage or the minimum payment threshold, in which case the new terms will be notified
				to You not less than thirty (30) days prior to the effective date and will be applicable to future
				incomes.
			</p>
			<p>
				<strong>4.7</strong> We may decide not to charge you initially for the use of the Service and
				any optional service, however, You authorize Us to deduct the corresponding amounts from your
				future payments.
			</p>
			<p>
				<strong>4.8</strong> Audits: We will maintain accurate and complete records of account including
				all documentation needed by You to compute and verify the fees payable to You in connection with
				the performance of our agreement.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Duration and Termination</Heading>
			<p>
				<strong>5.1</strong> The duration of our contractual relationship is initially undetermined. It
				shall begin when registering at the Platform and upon the explicit acceptance of these Terms of
				Use, and You or Us may elect to terminate the Service at any time by providing notice, in accordance
				with these Terms of Use, of thirty (30) days from the termination date.
			</p>
			<p>
				In the event of termination, You must pay all outstanding amounts to Us in a maximum period
				of five (5) days from the notification date or We will transfer to you any positive balance,
				whichever is the case.
			</p>
			<p><strong>5.2</strong> Additionally, We may terminate our relationship and the Service:</p>
			<ul class="list-disc pl-6 space-y-1">
				<li>
					in the event You breach any term or condition established by Us and You fail to remedy
					such breach within two (2) days of the date of notice from Us;
				</li>
				<li>in case the outstanding balance is not paid as per Section 4.7;</li>
				<li>
					if You become the subject of any proceeding related to your liquidation or insolvency;
				</li>
				<li>if You infringe our Intellectual Property Rights;</li>
				<li>if You infringe our Anti-Fraud Policy;</li>
				<li>in case you commit any unlawful activity using the Platform or the Service.</li>
			</ul>
			<p>
				<strong>5.3</strong> In all cases, all costs due for any Service provided by Us until the termination
				date, must be duly paid by You.
			</p>
			<p>
				<strong>5.4</strong> We will not be liable to You for damages of any kind because of the termination
				of our relationship in accordance with these Terms of Use.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Intellectual Property Rights</Heading>
			<p>
				<strong>6.1</strong> Nothing contained herein shall be construed as granting or conferring any
				property rights in the Platform or any part thereof to You; therefore, We are not granting to
				You by means of this Terms of Use, the right to exploit our Intellectual Property (including but
				not limited to copyright, patent, trademarks, registered marks, trade secrets, and confidential
				and proprietary information relating thereto).
			</p>
			<p>
				<strong>6.2</strong> When You upload any of Your Content to our servers through the Platform,
				you are recognizing the following:
			</p>
			<ul class="list-disc pl-6 space-y-1">
				<li>
					that We are authorized to administrate, directly or through third parties, Your Content
					through the Digital Music Services selected by You;
				</li>
				<li>
					that You own and/or control all rights in and to the Your Content and/or have the full
					right and ability to upload Your Content and exploit it;
				</li>
				<li>
					that Your Content does not infringe the copyrights or any other right, of any third party;
				</li>
				<li>
					that We are authorised during the Duration of the agreement, to grant to third parties
					synchronisation licences of Your Content for the entire world.
				</li>
			</ul>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Fraud</Heading>
			<p>
				<strong>7.1</strong> We work very hard and invest extensive resources to avoid automated and fraudulent
				behaviors. For this reason, we have created a specific Anti-Fraud Policy. When you accept these
				Terms of Use, you also acknowledge and accept our Anti-Fraud Policy and, therefore, You accept
				that, among other commitments, You will not, and will not authorize any third party to, directly
				or indirectly, generate automated, fraudulent, or otherwise invalid playback actions, especially
				in Digital Music Services.
			</p>
			<p>
				<strong>7.2</strong> In this Anti-Fraud Policy we have implemented a 3-strike policy; therefore,
				please, read carefully such policy as We will be very strict applying it.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Privacy</Heading>
			<p>
				<strong>8.1</strong> Our data protection policy is described in the Privacy Policy. The Privacy
				Policy is part of our relationship and, therefore, when you accept these Terms of Use, you are
				also acknowledging and accepting our Privacy Policy.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold"
				>Warranty. Limitation of Liability</Heading
			>
			<p>
				<strong>9.1</strong> We cannot warrant to You that the Platform and the Service will meet your
				requirements. Except as expressly provided in these Terms of Use, We provide the Services and
				the Platform "as is" and without warranty.
			</p>
			<p>
				<strong>9.2</strong> You will assume all liability and defend, indemnify, and hold Us and any
				party, harmless for the use of the Platform and the Service.
			</p>
			<p>
				<strong>9.3</strong> Our liability under or in connection with the Platform and the Service shall
				be limited to the value of the fees paid by You to Us during the 12 months prior to the claim.
			</p>
			<p>
				<strong>9.4</strong> We shall not be liable for any loss of profits, savings, goodwill, reputation,
				revenue, anticipated savings, business or opportunity or any other special, indirect, consequential
				or incidental losses or damages.
			</p>
			<p>
				<strong>9.5</strong> We respect the rights of others (including copyright, image and personality
				rights, etc.) and expect our clients to do the same.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Miscellaneous</Heading>
			<p>
				<strong>10.1</strong> Non-assignment: You may not assign your account or any interest therein
				to any third party, without our express prior written consent.
			</p>
			<p>
				<strong>10.2</strong> Severability: If any provision of this Agreement is found invalid or unenforceable,
				that provision will be enforced to the maximum extent permissible, and the other provisions of
				this Agreement will remain in force.
			</p>
			<p>
				<strong>10.3</strong> Promotion: We are not obliged to effectuate any online promotion and/or
				marketing of Your Content under these Terms of Use.
			</p>
			<p>
				<strong>10.4</strong> Notifications: Any notice that You or Us need to effectuate in connection
				with the development and performance of these Terms of Use shall be by email at the addresses
				listed on your account on the Platform.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold"
				>License Irrevocability and Takedown Policy</Heading
			>
			<p>
				<strong>11.1</strong> Irrevocable Grant: You acknowledge and agree that any rights and licenses
				granted to BBN Music GmbH in respect of Your Content are irrevocable with regard to all exploitations
				and distributions already made or initiated prior to any attempted revocation.
			</p>
			<p>
				<strong>11.2</strong> Prohibition of Abusive Notices: You may not, under any circumstances, submit
				or instruct any third party to submit a takedown notice against BBN Music GmbH, its partners,
				or any Content distributed by BBN Music GmbH that You have previously licensed or otherwise authorised.
			</p>
			<p>
				<strong>11.3</strong> Internal Resolution Process: Should You believe that Your rights have been
				violated, You must first notify Us in writing and engage in our internal resolution process. We
				will investigate and attempt to resolve the matter within thirty (30) days.
			</p>
			<p>
				<strong>11.4</strong> Consequences of Breach: Any User who submits a false, fraudulent, or abusive
				takedown notice, or otherwise breaches this Section, will be deemed in material breach of these
				Terms of Use.
			</p>
			<p>
				<strong>11.5</strong> Indemnity: To the fullest extent permitted by applicable law, You agree
				to indemnify and hold harmless BBN Music GmbH, its affiliates, officers, directors, employees,
				and agents from and against any claims, losses, liabilities, damages, costs and expenses arising
				out of or related to Your breach of this Section 11.
			</p>
		</section>

		<section>
			<Heading tag="h2" class="text-white text-xl font-bold">Dispute Resolution</Heading>
			<p>
				<strong>12.1</strong> Any dispute arising out of or relating to these Terms of Use shall first
				be submitted to Our internal resolution process described in Section 11.3. You agree to cooperate
				in good faith and supply all information reasonably requested.
			</p>
			<p>
				<strong>12.2</strong> If the dispute remains unresolved after completion of the internal process,
				it shall be finally settled in accordance with Section 10.7 (Law and Jurisdiction).
			</p>
		</section>

		<p class="text-sm text-gray-400 mt-8">Last updated: 2025-07-18</p>
	</div>
</div>
